/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csg;

/**
 *
 * @author spencernisonoff
 */
public enum CourseSiteGeneratorSitePropertyType {
    CSG_SITE_PANE,
    CSG_SITE_SCROLL_PANE,
    CSG_SITE_SUPER_BOX,
    CSG_SITE_PANE_V,
    CSG_SITE_LABEL,
    CSG_BANNER_LABEL,
    CSG_BANNER_PANE,
    CSG_BANNER_BOX1,
    CSG_BANNER_BOX2,
    CSG_BANNER_BOX3,
    CSG_BANNER_BOX4,
    CSG_SUBJECT_COMBO_BOX,
    CSG_SUBJECT_LABEL,
    CSG_NUMBER_COMBO_BOX,
    CSG_NUMBER_LABEL,
    CSG_SEMESTER_COMBO_BOX,
    CSG_SEMESTER_LABEL,
    CSG_FALL,
    CSG_SPRING,
    CSG_WINTER,
    CSG_SUMMER,
    CSG_YEAR_COMBO_BOX,
    CSG_YEAR_LABEL,
    CSG_SITE_TITLE_TEXT_FIELD,
    CSG_SITE_TITLE_LABEL,
    CSG_EXPORT_DIR_LABEL,
    CSG_EXPORT_DIRECTORY,
    CSG_PAGES_LABEL,
    CSG_PAGES_PANE,
    CSG_HOME_CHECK_BOX,
    CSG_SYLLABUS_CHECK_BOX,
    CSG_SCHEDULE_CHECK_BOX,
    CSG_HWS_CHECK_BOX,
    CSG_STYLE_LABEL,
    CSG_STYLE_PANE,
    CSG_FAVICON_BOX,
    CSG_FAVICON_BUTTON,
    CSG_FAVICON_IMAGE,
    CSG_NAVBAR_BOX,
    CSG_NAVBAR_BUTTON,
    CSG_NAVBAR_IMAGE,
    CSG_LEFT_FOOTER_BOX,
    CSG_LEFT_FOOTER_BUTTON,
    CSG_LEFT_FOOTER_IMAGE,
    CSG_RIGHT_FOOTER_BOX,
    CSG_RIGHT_FOOTER_BUTTON,
    CSG_RIGHT_FOOTER_IMAGE,
    CSG_CSS_BOX,
    CSG_FONTS_AND_COLORS_STYLE_SHEET_LABEL,
    CSG_FONTS_AND_COLORS_STYLE_SHEET_COMBO_BOX,
    CSG_NOTE_LABEL,
    
    
    // ALL OF THESE PROPERTIES RELATE TO THE INSTRUCTOR 
    CSG_INSTRUCTOR_PANE,
    CSG_INSTRUCTOR_LABEL,
    CSG_INSTRUCTOR_NAME_LABEL,
    CSG_INSTRUCTOR_NAME_TEXT_FIELD,
    CSG_INSTRUCTOR_PLUS_MINUS_BUTTON,
    CSG_INSTRUCTOR_BOX_1,
    CSG_INSTRUCTOR_BOX_2,
    CSG_INSTRUCTOR_BOX_3,
    CSG_INSTRUCTOR_ROOM_LABEL,
    CSG_INSTRUCTOR_ROOM_TEXT_FIELD,
    CSG_INSTRUCTOR_EMAIL_LABEL,
    CSG_INSTRUCTOR_EMAIL_TEXT_FIELD,
    CSG_HOME_PAGE_LABEL,
    CSG_HOME_PAGE_TEXT_FIELD,
    CSG_OFFICE_HOURS_LABEL,
    CSG_OFFICE_HOURS_TEXT_AREA
}
