/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csg;

/**
 *
 * @author spencernisonoff
 */
public enum CourseSiteGeneratorSyllabusPropertyType {
    CSG_SYLLABUS_PANE,
    CSG_SYLLABUS_SCROLL_PANE,
    CSG_DESCRIPTION_PANE,
    CSG_DESCIPTION_LINE,
    CSG_DESCRIPTION_BUTTON,
    CSG_DESCRIPTION_LABEL,
    CSG_DESCRIPTION_TEXT_AREA,
    CSG_DESCRIPTION_TEXT_BOX,
    CSG_TOPICS_PANE,
    CSG_TOPICS_LABEL,
    CSG_TOPICS_LINE,
    CSG_TOPICS_BUTTON,
    CSG_TOPICS_TEXT_AREA,
    CSG_TOPICS_TEXT_BOX,
    CSG_PREREQUISITES_LINE,
    CSG_PREREQUISITES_PANE,
    CSG_PREREQUISITES_LABEL,
    CSG_PREREQUISITES_BUTTON,
    CSG_PREREQUISITES_TEXT_AREA,
    CSG_PREREQUISITES_TEXT_BOX,
    CSG_OUTCOMES_LINE,
    CSG_OUTCOMES_LABEL,
    CSG_OUTCOMES_PANE,
    CSG_OUTCOMES_BUTTON,
    CSG_OUTCOMES_TEXT_AREA,
    CSG_OUTCOMES_TEXT_BOX,
    CSG_TEXTBOOKS_LINE,
    CSG_TEXTBOOKS_LABEL,
    CSG_TEXTBOOKS_PANE,
    CSG_TEXTBOOKS_BUTTON,
    CSG_TEXTBOOKS_TEXT_AREA,
    CSG_TEXTBOOKS_TEXT_BOX,
    CSG_GRADED_COMPONENTS_LINE,
    CSG_GRADED_COMPONENTS_LABEL,
    CSG_GRADED_COMPONENTS_PANE,
    CSG_GRADED_COMPONENTS_BUTTON,
    CSG_GRADED_COMPONENTS_TEXT_AREA,
    CSG_GRADED_COMPONENTS_TEXT_BOX,
    CSG_GRADING_NOTE_LINE,
    CSG_GRADING_NOTE_LABEL,
    CSG_GRADING_NOTE_PANE,
    CSG_GRADING_NOTE_BUTTON,
    CSG_GRADING_NOTE_TEXT_AREA,
    CSG_GRADING_NOTE_TEXT_BOX,
    CSG_ACADEMIC_DISHONESTY_LINE,
    CSG_ACADEMIC_DISHONESTY_PANE,
    CSG_ACADEMIC_DISHONESTY_LABEL,
    CSG_ACADEMIC_DISHONESTY_BUTTON,
    CSG_ACADEMIC_DISHONESTY_TEXT_AREA,
    CSG_ACADEMIC_DISHONESTY_TEXT_BOX,
    CSG_SPECIAL_ASSISTANCE_LINE,
    CSG_SPECIAL_ASSISTANCE_LABEL,
    CSG_SPECIAL_ASSISTANCE_PANE,
    CSG_SPECIAL_ASSISTANCE_BUTTON,
    CSG_SPECIAL_ASSISTANCE_TEXT_AREA,
    CSG_SPECIAL_ASSISTANCE_TEXT_BOX,
    CSG_ILLEGAL_START_END_DATE_TITLE,
    CSG_ILLEGAL_START_END_DATE_CONTENT
}
