/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csg;

/**
 *
 * @author spencernisonoff
 */
public enum CourseSiteGeneratorSchedulePropertyType {
    CSG_SCHEDULE_SCROLL_PANE,
    CSG_SCHEDULE_PANE,
    CSG_CALANDAR_BOUNDARIES_LABEL,
    CSG_CALANDAR_BOUNDARIES_PANE,
    CSG_START_END_BOX,
    CSG_STARTING_MONDAY_LABEL,
    CSG_STARTING_MONDAY_DATE_PICKER,
    CSG_ENDING_FRIDAY_LABEL,
    CSG_ENDING_FRIDAY_DATE_PICKER,
    CSG_SCHEDULE_ITEMS_PANE,
    CSG_SCHEDULE_ITEMS_BOX,
    CSG_SCHEDULE_ITEMS_BUTTON,
    CSG_SCHEDULE_ITEMS_LABEL,
    CSG_SCHEDULE_ITEMS_TABLE_VIEW,
    CSG_ADD_EDIT_PANE,
    CSG_ADD_EDIT_LABEL,
    CSG_SCHEDULE_TYPE_COLUMN,
    CSG_SCHEDULE_DATE_COLUMN,
    CSG_SCHEDULE_TITLE_COLUMN,
    CSG_SCHEDULE_TOPIC_COLUMN,
    CSG_SCHEDULE_TYPE_BOX,
    CSG_SCHEDULE_TYPE_LABEL,
    CSG_SCHEDULE_TYPE_COMBO_BOX,
    CSG_SCHEDULE_DATE_BOX,
    CSG_SCHEDULE_DATE_LABEL,
    CSG_SCHEDULE_DATE_DATE_PICKER,
    CSG_SCHEDULE_TITLE_BOX,
    CSG_SCHEDULE_TITLE_LABEL,
    CSG_SCHEDULE_TITLE_TEXT_FIELD,
    CSG_SCHEDULE_TOPIC_BOX,
    CSG_SCHEDULE_TOPIC_LABEL,
    CSG_SCHEDULE_TOPIC_TEXT_FIELD,
    CSG_SCHEDULE_LINK_BOX,
    CSG_SCHEDULE_LINK_LABEL,
    CSG_SCHEDULE_LINK_TEXT_FIELD,
    CSG_SCHEDULE_BUTTON_BOX,
    CSG_SCHEDULE_ADD_UPDATE_BUTTON,
    CSG_SCHEDULE_CLEAR_BUTTON,
    
    CSG_HOLIDAY,
    CSG_LECTURE,
    CSG_RECITATION,
    CSG_LAB,
    CSG_HW,
    CSG_EXAM,
    CSG_QUIZ
}
