/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csg;

/**
 *
 * @author spencernisonoff
 */
public enum CourseSiteGeneratorMeetingTimesPropertyType {
    CSG_MEETING_TIMES_SCROLL_PANE,
    CSG_MEETING_TIMES_PANE,
    CSG_MEETING_TIMES_LABEL,
    CSG_LECTURES_PANE,
    CSG_LECTURES_LABEL,
    CSG_LECTURES_PLUS_BUTTON,
    CSG_LECTURES_MINUS_BUTTON,
    CSG_LECTURES_TABLE_VIEW,
    CSG_LECTURES_BOX,
    CSG_SECTION_COLUMN,
    CSG_DAYS_COLUMN,
    CSG_TIME_COLUMN,
    CSG_ROOM_COLUMN,
    CSG_RECITATIONS_PANE,
    CSG_RECITATIONS_BOX,
    CSG_RECITATIONS_LABEL,
    CSG_RECITATIONS_PLUS_BUTTON,
    CSG_RECITATIONS_MINUS_BUTTON,
    CSG_RECITATIONS_TABLE_VIEW,
    CSG_RECITATIONS_SECTION_COLUMN,
    CSG_RECITATIONS_ROOM_COLUMN,
    CSG_RECITATIONS_DAYS_AND_TIMES_COLUMN,
    CSG_RECITATIONS_TA1_COLUMN,
    CSG_RECITATIONS_TA2_COLUMN,
    CSG_LABS_PANE,
    CSG_LABS_BOX,
    CSG_LABS_LABEL,
    CSG_LABS_PLUS_BUTTON,
    CSG_LABS_MINUS_BUTTON,
    CSG_LABS_TABLE_VIEW,
    CSG_LABS_SECTION_COLUMN,
    CSG_LABS_ROOM_COLUMN,
    CSG_LABS_DAYS_AND_TIMES_COLUMN,
    CSG_LABS_TA1_COLUMN,
    CSG_LABS_TA2_COLUMN
}
